name: setup-python
description: Setup Python with optional pip caching
inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.11'
  cache:
    description: 'pip cache: "pip" or empty'
    required: false
runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache || '' }}
