name: cdk-deploy-env
on:
  workflow_call:
    inputs:
      artifact-name: { type: string, default: 'lambda-bundle' }
      cdk-dir: { type: string, required: true }
      stack: { type: string, required: true }
      aws-account: { type: string, required: true }
      aws-region: { type: string, default: 'us-west-2' }
      role-to-assume: { type: string, required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout caller repository (consumer)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact (caller-run)
        uses: actions/download-artifact@v4
        with:
          name: lambda-bundle
          path: ./artifact/*

      - name: Prepare artifact into CDK dir
        run: |
          set -e
          mkdir -p ${{ inputs.cdk-dir }}/assets
          cp -R ./artifact/* ${{ inputs.cdk-dir }}/assets/ || true

      - name: Install CDK deps
        working-directory: ${{ inputs.cdk-dir }}
        run: |
          python -m pip install -r requirements.txt || true
          npm ci --silent || true

      - name: CDK synth
        working-directory: ${{ inputs.cdk-dir }}
        run: npx cdk@latest synth

      - name: CDK deploy
        working-directory: ${{ inputs.cdk-dir }}
        run: npx cdk@latest deploy ${{ inputs.stack }} --require-approval never