name: oidc-safe-debug
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show context
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "RUNNER_NAME=$RUNNER_NAME"
          echo "RUNNER_OS=$RUNNER_OS"
          echo "ACTIONS_ID_TOKEN_REQUEST_URL=${ACTIONS_ID_TOKEN_REQUEST_URL:-<not-set>}"

      - name: Fetch ID token (if URL exposed)
        run: |
          if [ -z "${ACTIONS_ID_TOKEN_REQUEST_URL:-}" ]; then
            echo "ACTIONS_ID_TOKEN_REQUEST_URL not set; configure action will request token internally."
            exit 0
          fi
          # fetch token JSON and extract token to /tmp/id_token.jwt
          resp=$(curl -fsS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" || true)
          echo "raw response (truncated):"
          printf '%s\n' "$resp" | jq -C . || true
          token=$(echo "$resp" | jq -r '.value // .id_token // .token // empty')
          if [ -z "$token" ]; then
            echo "no token extracted"; exit 0
          fi
          printf '%s' "$token" > /tmp/id_token.jwt
          echo "/tmp/id_token.jwt written"

      - name: Decode token payload (repo script)
        run: |
          if [ -f /tmp/id_token.jwt ]; then
            python3 scripts/decode_jwt.py /tmp/id_token.jwt
          else
            echo "/tmp/id_token.jwt not present; skipping decode"
          fi

      - name: Attempt manual STS assume-role-with-web-identity
        env:
          ROLE_ARN: arn:aws:iam::444101352833:role/gha-cdk-deploy-dev
        run: |
          if [ -f /tmp/id_token.jwt ]; then
            aws sts assume-role-with-web-identity \
              --role-arn "$ROLE_ARN" \
              --role-session-name debug-session \
              --web-identity-token file:///tmp/id_token.jwt || true
          else
            echo "no token file; skipping manual assume-role test"
          fi

      - name: Try configure-aws-credentials action
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::444101352833:role/gha-cdk-deploy-dev
          aws-region: us-west-2

      - name: whoami
        run: aws sts get-caller-identity --output json || true
